apk: android
gradle: android
ds_store: apple
localized: apple
flac: audio
m4a: audio
mp3: audio
ogg: audio
wav: audio
brewfile: brew
cfg: conf
editorconfig: conf
scss: css
docx: doc
gdoc: doc
mobi: ebook
eot: font
otf: font
ttf: font
woff: font
woff2: font
gitconfig: git
gitflow_export: git
gitignore: git
gitignore_global: git
lhs: hs
bmp: image
gif: image
ico: image
jpeg: image
jpg: image
png: image
pxm: image
svg: image
tiff: image
webp: image
jar: java
properties: json
tsx: jsx
license: md
markdown: md
mkd: md
rdoc: md
readme: md
nanorc: nano
netrc: netrc
gslides: ppt
pptx: ppt
ipynb: py
pyc: py
rdata: r
rds: r
gemfile: rb
gemspec: rb
guardfile: rb
lock: rb
procfile: rb
rakefile: rb
rspec: rb
rspec_parallel: rb
rspec_status: rb
ru: rb
erb: rubydoc
slim: rubydoc
aliases: shell
bash: shell
bash_history: shell
bash_profile: shell
bashrc: shell
exports: shell
fish: shell
functions: shell
liquidpromptrc: shell
nowplaying: shell
profile: shell
rcrc: shell
sh: shell
zsh: shell
zshenv: shell
zsh-theme: shell
zshrc: shell
stylus: styl
cls: tex
avi: video
flv: video
mkv: video
mov: video
mp4: video
ogv: video
webm: video
bat: windows
exe: windows
ini: windows
csv: xls
gsheet: xls
xlsx: xls
xul: xml
yaml: yml
gz: zip
rar: zip
tar: zip
