#!/usr/bin/env bash
# Create a new directory and enter it
function mkd() {
	mkdir -p "$@" && cd "$_";
}


# who is using the laptop's iSight camera?
# thanks to https://github.com/paulirish/ for this!
camerausedby() {
	echo "Checking to see who is using the iSight camera… 📷"
	usedby=$(lsof | grep -w "AppleCamera\|USBVDC\|iSight" | awk '{printf $2"\n"}' | xargs ps)
	echo -e "Recent camera uses:\n$usedby"
}

# List all files, long format, colorized, permissions in octal
# function la(){
#  	ls -l  "$@" | awk '
#    {
#      k=0;
#       for (i=0;i<=8;i++)
#         k+=((substr($1,i+2,1)~/[rwx]/) *2^(8-i));
#      if (k)
#         printf("%0o ",k);
#     printf(" %9s  %3s %2s %5s  %6s  %s %s %s\n", $3, $6, $7, $8, $5, $9,$10, $11);
#     }'
# }

# animated gifs from any video
# from alex sexton   gist.github.com/SlexAxton/4989674
gifify() {
  if [[ -n "$1" ]]; then
	if [[ $2 == '--good' ]]; then
	  ffmpeg -i "$1" -r 10 -vcodec png out-static-%05d.png
	  time convert -verbose +dither -layers Optimize -resize 900x900\> out-static*.png  GIF:- | gifsicle --colors 128 --delay=5 --loop --optimize=3 --multifile - > "$1.gif"
	  rm out-static*.png
	else
	  ffmpeg -i "$1" -s 600x400 -pix_fmt rgb24 -r 10 -f gif - | gifsicle --optimize=3 --delay=3 > "$1.gif"
	fi
  else
	echo "proper usage: gifify <input_movie.mov>. You DO need to include extension."
  fi
}
